#!/usr/bin/env python3
"""
Generate Merged_lecture_notes.tex from the 21 individual lecture .tex files.

Strategy:
  - Single shared preamble (union of packages across all lectures)
  - \\graphicspath covers every lecture directory so figures resolve correctly
  - hyperref + bookmark packages add PDF outline entries for each lecture
  - Body of each file (between \\begin{document} and \\end{document}) is
    inlined after a \\pdfbookmark call so the PDF has a proper outline.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent   # METU-EE302/
PWD = Path(__file__).resolve().parent          # Merge_Lecture_Notes/
NUM_LECTURES = 21

# ── 1. collect lecture file paths ──────────────────────────────────────────

def find_tex(lecture_num: int) -> Path:
    folder = ROOT / f"Lecture {lecture_num}"
    tex_files = list(folder.glob("*.tex"))
    if not tex_files:
        raise FileNotFoundError(f"No .tex found in {folder}")
    return tex_files[0]

lecture_files = [find_tex(n) for n in range(1, NUM_LECTURES + 1)]

# ── 2. extract body content ────────────────────────────────────────────────

def extract_body(path: Path) -> str:
    """Return everything strictly between \\begin{document} and \\end{document}."""
    text = path.read_text(encoding="utf-8")
    m = re.search(r'\\begin\{document\}(.*?)\\end\{document\}', text,
                  re.DOTALL)
    if not m:
        raise ValueError(f"Could not find document body in {path}")
    return m.group(1).strip()

# ── 3. helper: rewrite \includegraphics paths to absolute ───────────────

INCLUDE_RE = re.compile(
    r'(\\includegraphics\s*(?:\[[^\]]*\])?\s*)\{([^}]+)\}'
)

def absolutify_graphics(body: str, folder: Path) -> str:
    """Replace bare filenames in \\includegraphics{} with absolute paths."""
    def _replace(m: re.Match) -> str:
        cmd   = m.group(1)
        fname = m.group(2).strip()
        # already absolute or contains a slash -> leave alone
        if fname.startswith('/') or '/' in fname:
            return m.group(0)
        return cmd + '{' + (folder / fname).as_posix() + '}'
    return INCLUDE_RE.sub(_replace, body)

# ── 4. preamble ────────────────────────────────────────────────────────────

PREAMBLE = r"""% ============================================================
%  EE302 – Feedback Systems  |  Merged Lecture Notes  (1–21)
%  Lecturer: Asst. Prof. M. Mert Ankarali
%  Auto-generated by generate_merged.py
% ============================================================

\documentclass[twoside]{article}
\setlength{\oddsidemargin}{0.25 in}
\setlength{\evensidemargin}{-0.25 in}
\setlength{\topmargin}{-0.6 in}
\setlength{\textwidth}{6.5 in}
\setlength{\textheight}{8.5 in}
\setlength{\headsep}{0.75 in}
\setlength{\parindent}{0 in}
\setlength{\parskip}{0.1 in}

% ── packages ──────────────────────────────────────────────────────────────
\usepackage{amsmath,amsfonts,graphicx}
\usepackage{amsthm}
\usepackage{mathdots}
\usepackage[
  bookmarks=true,
  bookmarksopen=true,
  bookmarksnumbered=false,
  hidelinks
]{hyperref}
\usepackage{bookmark}

% ── lecture counter & numbering ──────────────────────────────────────────
\newcounter{lecnum}
\renewcommand{\thepage}{\thelecnum-\arabic{page}}
\renewcommand{\thesection}{\thelecnum.\arabic{section}}
\renewcommand{\theequation}{\thelecnum.\arabic{equation}}
\renewcommand{\thefigure}{\thelecnum.\arabic{figure}}
\renewcommand{\thetable}{\thelecnum.\arabic{table}}

% ── lecture header macro ─────────────────────────────────────────────────
\newcommand{\lecture}[2]{
   \pagestyle{myheadings}
   \thispagestyle{plain}
   \newpage
   \setcounter{lecnum}{#1}
   \setcounter{page}{1}
   \setcounter{section}{0}
   \setcounter{subsection}{0}
   \setcounter{subsubsection}{0}
   \setcounter{equation}{0}
   \setcounter{figure}{0}
   \setcounter{table}{0}
   \noindent
   \begin{center}
   \framebox{
      \vbox{\vspace{2mm}
    \hbox to 6.28in { {\bf EE302 - Feedback Systems
        \hfill Spring 2019} }
       \vspace{4mm}
       \hbox to 6.28in { {\Large \hfill Lecture #1 \hfill} }
       \vspace{2mm}
       \hbox to 6.28in { {\it Lecturer: #2 \hfill } }
      \vspace{2mm}}
   }
   \end{center}
   \markboth{Lecture #1}{Lecture #1}
   \vspace*{4mm}
}

% ── citation / bibliography helpers ─────────────────────────────────────
\renewcommand{\cite}[1]{[#1]}
\def\beginrefs{\begin{list}%
        {[\arabic{equation}]}{\usecounter{equation}
         \setlength{\leftmargin}{2.0truecm}\setlength{\labelsep}{0.4truecm}%
         \setlength{\labelwidth}{1.6truecm}}}
\def\endrefs{\end{list}}
\def\bibentry#1{\item[\hbox{[#1]}]}

% ── figure placeholder macro ─────────────────────────────────────────────
\newcommand{\fig}[3]{
    \vspace{#2}
    \begin{center}
    Figure \thelecnum.#1:~#3
    \end{center}
}

% ── theorem environments ─────────────────────────────────────────────────
\newtheorem{theorem}{Theorem}[lecnum]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{proposition}[theorem]{Proposition}
\newtheorem{claim}[theorem]{Claim}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{definition}[theorem]{Definition}
\newtheorem{exmp}[theorem]{Ex}
\renewenvironment{proof}{{\bf Proof:}}{\hfill\rule{2mm}{2mm}}
"""

# ── 5. assemble document body ──────────────────────────────────────────────

def make_lecture_block(num: int, body: str) -> str:
    """Wrap the raw body with a PDF bookmark for the lecture outline entry."""
    label = f"lecture{num}"
    bookmark = (
        f"% {'='*60}\n"
        f"% Lecture {num}\n"
        f"% {'='*60}\n"
        f"\\pdfbookmark[0]{{Lecture {num}}}{{{label}}}\n"
    )
    return bookmark + body + "\n"

body_blocks = []
for n, path in enumerate(lecture_files, start=1):
    print(f"  reading Lecture {n}: {path.name}")
    body = extract_body(path)
    body = absolutify_graphics(body, path.parent)
    body_blocks.append(make_lecture_block(n, body))

# ── 6. write the merged file ───────────────────────────────────────────────

OUT = PWD / "Merged_lecture_notes.tex"

content = (
    PREAMBLE
    + "\n\\begin{document}\n\n"
    + "\n".join(body_blocks)
    + "\n\\end{document}\n"
)

OUT.write_text(content, encoding="utf-8")
print(f"\nWrote {OUT}")
print(f"Total characters: {len(content):,}")
